### ISSUE TITLE
Migrate the codebase from Gatekeeper repository

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#516]
## What

Move the codebase from https://github.com/keycloak/keycloak-gatekeeper to https://github.com/louketo

## Why

We agreed that would be a good idea to use Gatekeeper codebase as a starting point for development, so we could iterate over it.

## How

Move the codebase to louketo repository by preserving Git history

**Comment by stianst** [comment]
I thought we where going to just move the repo? Not clone it.

**Comment by abstractj** [comment]
@stianst fixed :)

**Comment by jangaraj** [comment]
Are there any public details about future of this repo? Why it will be moved to Louketo and what is Louketo?

**Comment by mreinli** [comment]
Yes, would also be interesting to hear about the plans here.

**Comment by abstractj** [comment]
@jangaraj @mreinli please give me few hours, I will follow up on the dev mailing list.

**Comment by abstractj** [comment]
@jangaraj @mreinli please let me know if it helps to clarify this issue https://groups.google.com/forum/#!topic/keycloak-dev/oDyw94BWxM0. If not, please do not hesitate to ask me any questions on the same thread.

**Comment by abstractj** [comment]
Resolved by https://github.com/louketo/louketo-proxy/pull/603
