### ISSUE TITLE
Create a GitHub templates for pull-requests and new issues

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#522]
## What
Update our GitHub templates for new issues and PR submissions

## Why
Our current GitHub templates point people to the Keycloak contribution URL which almost all the time nobody reads. We need to provide a more straightforward template for people to add as much details as they can.

For feature requests, if the reviewers have a clear understanding of what the PR solves and how to test it. This may help our review process because people don't need to spend time asking for more details. Newcomers have a chance to try the steps mentioned.

For bugs, people will understand what is the "Expected result" and even if they don't know the codebase, they are at least able to review and give it a try.

## How
* See: https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file

**Comment by statik** [comment]
Thanks for doing this! I am very happy to see this happening, I think it will make it easier to participate and contribute.
