### ISSUE TITLE
 You have not specified the listening interface - error

### ISSUE THREAD

**Issue by rogerioefonseca** [louketo/louketo-proxy#530]
I know that I only have to pass the config parameter, but would be nice to document it on the README like bitnami made. 

https://github.com/bitnami/bitnami-docker-keycloak-gatekeeper#using-a-configuration-file

**Comment by bpasson** [comment]
Feel free to assign it to me. I already submitted a PR for it as you can see.

**Comment by abstractj** [comment]
Resolved by #608
