### ISSUE TITLE
Escaped slashes unescaped by Gatekeeper proxy

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#591]
## What: 

  Hello all,
  
  The Gatekeeper proxy unescapes slashes in the URL path.
  
  h3. The problem
  A request like:
  
  http://127.0.0.1:8080/iiif/2/edepot_local:ST%2F00001%2FST00005_00001.jpg/full/1000,/0/default.png
  
  is passed to the upstream as:
  
  http://127.0.0.1:8080/iiif/2/edepot_local:ST/00001/ST00005_00001.jpg/full/1000,/0/default.png
  
  Note that "*%2F*" is transformed to "*/*".
  
  I expect a reverse proxy to not modify the URL to this extend. But the encoded slashes are unencoded at two different points by Gatekeeper now.
  
  # If not authenticated the path that is restored after login transforms the escaped slashes.
  # The proxy code itself transforms escaped slashes to slashes.
  
  h3. Solution
  Decoding escaped parts by the proxy seems like a problem to me. I suggest the proxy passes along the URL as is. Possibly by setting a configuration.
  
  I'm not very familiar with GO, but I might be able to open a PR with a possible solution.

## Reference:

- [KEYCLOAK-11276 - Escaped slashes unescaped by Gatekeeper proxy](https://issues.redhat.com/browse/KEYCLOAK-11276)

Relates to #594

**Comment by Nuru** [comment]
Fixed in #535

**Comment by abstractj** [comment]
Solved in https://github.com/louketo/louketo-proxy/pull/626. Thanks to @Nuru
