### ISSUE TITLE
Run golangci-lint as part of pull request workflow

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#604]
## What

Unfortunately [GolangCI is closing](https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e) and we need to migrate to another alternative. So we can have a sanity check for upcoming pull requests.

## How

* GolangCI service was closed, but the linter [golangci-lint](https://github.com/golangci/golangci-lint) will be maintained, which means that we can benefit from this using GitHub actions.

## Additional information

* [golangci-lint-action](https://github.com/marketplace/actions/run-golangci-lint)

**Comment by JoelSpeed** [comment]
I've not used codeclimate before, but it seems like it suggests sensible improvements. I'd be intrigued to see what happens if you put up something that is considered bad form, will it comment on the PR? 

I noticed it has also scanned master for issues, is there a way to mark those as false positives? Eg I noticed one is the config validation having too many returns, that would probably be an exception right?

**Comment by abstractj** [comment]
Hi @JoelSpeed, yes it will add comments on the PR, but probably we might need to customize to our own needs to prevent false positives and some annoyance. You can have an idea of looking at these links:

- [Pull Request Review Comments](https://docs.codeclimate.com/docs/github-pull-requests#section-pull-request-review-comments)
- [Pull Request Statuses](https://docs.codeclimate.com/docs/github-pull-requests#section-pull-request-statuses)

Unfortunately, GolangCI will no longer available and these are the only alternatives I can think at the moment:

1. Remove GolangCI and no longer have any feedback on pull requests. That's perfectly fine, as
long as we introduce a process for people to check their code before submitting or merging it.
2. Move to another CI that it does something similar, like Code Climate.

If you have any other ideas, please do not hesitate to comment here.

**Comment by abstractj** [comment]
Btw I'm removing it from milestone 1.0.0, so we don't need to rush on the decision about this.

**Comment by abstractj** [comment]
@JoelSpeed updated the description and the content too. I believe this alternative makes more sense and it is something which we are already familiar.
