### ISSUE TITLE
Docker image from readme is private

### ISSUE THREAD

**Issue by freiit** [louketo/louketo-proxy#606]
```
$ docker pull quay.io/louketo/louketo-proxy
Using default tag: latest
Error response from daemon: unauthorized: access to the requested resource is not authorized
```

**Comment by abstractj** [comment]
Affects #541

**Comment by Ryonez** [comment]
Is there a way to get this, or is it not ready?

Keycloak's update to 10.0.0 has enforced strict scope rules, and the current "Official" gatekeeper image is broken.

**Comment by abstractj** [comment]
@Ryonez could you please elaborate why the Gatekeeper image is broken?

**Comment by Ryonez** [comment]
Was this issue here, discovered to be user error. Scope was added in the config file.
https://issues.redhat.com/browse/KEYCLOAK-14250

**Comment by abstractj** [comment]
@Ryonez @freiit should be fixed now. But please reopen, if that's not the case.
