### ISSUE TITLE
Why does louketo send User Agents to the authorization server with 307?

### ISSUE THREAD

**Issue by ackerleytng** [louketo/louketo-proxy#627]
## Summary 

Was testing a protected endpoint using POST, and I was redirected to `/oauth/authorize` on louketo with a 307, and then subsequently redirected to my authorization server (Keycloak) with a 307.

## Environment

Looking at https://github.com/louketo/louketo-proxy/blob/f623dee81736ee53ab3ec531b550496a76b8231f/handlers.go#L70

(Not environment specific)

## Expected Results

I thought we should be sending User-Agents to the authorization server with a 303, as 303 hints the User-Agent to use a GET (https://tools.ietf.org/html/rfc2616#section-10.3.4)

I think the method itself isn't so much of an issue, but sending a 307 suggests that the User-Agent [can repeat the original request on the new URI](https://tools.ietf.org/html/rfc2616#section-10.3.8), which might leak something to the authorization provider.

## Actual Results

Louketo tries to send the User-Agent to the authorization server with a 307.

## Steps to reproduce

Set up louketo to proxy a protected endpoint and try POSTing to an endpoint requiring authentication

## Additional Information

Related question: In [redirectToAuthorization](https://github.com/louketo/louketo-proxy/blob/f623dee81736ee53ab3ec531b550496a76b8231f/misc.go#L94), why is the default 307? I was thinking that there isn't really a reason to have 307, since 307 would encourage the User-Agent to repeat the original request on the new URI, with the original method and data, etc, which probably isn't necessary since louketo's /oauth/authorize endpoint isn't going to make use of all that.

**Comment by abstractj** [comment]
@ackerleytng thanks for reporting this, it should be fixed here https://github.com/louketo/louketo-proxy/pull/628. Please review, whenever you have some time.

**Comment by ackerleytng** [comment]
Thanks @abstractj , it looks great! I've also left a comment on your PR.
