### ISSUE TITLE
Rename all the old Git tags

### ISSUE THREAD

**Issue by abstractj** [louketo/louketo-proxy#629]
## Summary 

Rename all the old Git tags from this repository to avoid any confusion in the further releases.

## Why?

We have several Git tags created during the Gatekeeper releases. Now with Louketo, we're going to start on
Git tag 1.0.0. 

The best way of doing this while still preserving the tags, is to rename all the tags to something like:
`10.0.0-gatekeeper`

## How

* Run all the tags locally
* Push them

## Acceptance criteria

* All the tags renamed with the suffix `-gatekeeper`

**Comment by abstractj** [comment]
@stianst @ASzc could you please review this idea and let me know if makes sense to you guys?

**Comment by stianst** [comment]
I would probably go with a prefix rather than suffix, and something that sorts at the end of the list in GitHub UI to get them out of the way. Will Louketo use vX.Y.Z or X.Y.Z format for tags? If the former then I'd probably rename existing tags to something like "xGatekeeper-vX.Y.Z"

**Comment by ASzc** [comment]
I agree with Stian's point about sorting.

Here's a script to do the renaming:

```
#!/bin/bash -ex

git fetch --tags origin
while read -r tag
do
    git push origin "refs/tags/$tag:refs/tags/xGatekeeper-$tag"
    git push -d origin "refs/tags/$tag"
    git tag -d "$tag"
done < <(git tag -l | grep -v '^xGatekeeper')
```

Anyone with an existing fork on GitHub will need to run the same script to have a clean fork. People who just have a local clone only can most easily just re-clone.

**Comment by abstractj** [comment]
> I would probably go with a prefix rather than suffix, and something that sorts at the end of the list in GitHub UI to get them out of the way. Will Louketo use vX.Y.Z or X.Y.Z format for tags? If the former then I'd probably rename existing tags to something like "xGatekeeper-vX.Y.Z"

Thanks will do that. Answering your question, I'd like to stick with X.Y.Z as [vX.Y.Z is not considered a semantic version](https://semver.org/#is-v123-a-semantic-version).

@ASzc thank you! I will give your script a try at my fork

**Comment by abstractj** [comment]
@ASzc @stianst it turns out that using the prefix suggested won't sort it to the end once we release 1.0.0. See the image below:

![](https://i.imgur.com/oYzxGSu.gif)

### Some alternatives

1. For releases, create tags with the `v` prefix, like `v1.0.0`. Honestly I don't like this idea, because it's a workaround, only to sort GH tags and it's not a semantic version.
2. Use the original proposal of having `xGatekeeper-10.0.0`, maybe rename to `old_Gatekeeper-10.0.0` and live with the fact that new releases won't move to the top.

Thoughts? Once we agree about this, I will proceed with the changes.

**Comment by ASzc** [comment]
Seems they use a reverse sort, so a lot of the usual tricks to get something to the end of a list don't work, as you've discovered.

What about prefixing the new version tags too?

Pattern for old tags: `gatekeeper-$oldtag`

Pattern for new tags: `louketo-proxy-1.0.0`

This happens to sort the way we want, at least in my trials with `sort -Vr` on the command line, although I haven't tested it on GitHub itself.

**Comment by abstractj** [comment]
+1 we just need to change the remember to change the YAML files from #615 to remove the prefix. But I believe is a great alternative.

@stianst wdyt?

**Comment by stianst** [comment]
I think the ideal is to have the new tags just x.y.z and I'm not to keen on prefixing those with louketo-proxy.

What about "0.9.0-gatekeeper-x.y.z" or something like that?

**Comment by ASzc** [comment]
That would work from a sorting perspective.

**Comment by abstractj** [comment]
@ASzc @stianst I just tweaked Alex's script to:

```
#!/bin/bash -ex

git fetch --tags origin
while read -r tag
do
    git push origin "refs/tags/$tag:refs/tags/0.$tag-Gatekeeper"
    git push -d origin "refs/tags/$tag"
    git tag -d "$tag"
done < <(git tag -l | grep -v '^-Gatekeeper')

```

Below is the outcome:

![](https://imgur.com/dNknRRd.gif)

If you guys agree about this I will move forward with the changes.

**Comment by ASzc** [comment]
If the script is to avoid touching already converted tags, then the grep pattern should be `-Gatekeeper$`

**Comment by abstractj** [comment]
@ASzc using `grep -v '-Gatekeeper$'` returns an invalid pattern here. Maybe we should just change to `grep -v '*-Gatekeeper$'`. Wdyt?

**Comment by ASzc** [comment]
Oh, oops, that's because grep needs `-e` before a pattern that starts with a `-`, to avoid interpreting the pattern as arguments. Prepending `.*` is also a valid workaround.

**Comment by abstractj** [comment]
Thanks @ASzc. Script updated:

```
#!/bin/bash -ex

git fetch --tags origin
while read -r tag
do
    git push origin "refs/tags/$tag:refs/tags/0.$tag-Gatekeeper"
    git push -d origin "refs/tags/$tag"
    git tag -d "$tag"
done < <(git tag -l | grep -v -e '-Gatekeeper$')

```

### Outcome

![](https://imgur.com/6zw7Vad.gif)

@stianst if you agree, I believe now we're good to go.

**Comment by stianst** [comment]
LGTM

**Comment by abstractj** [comment]
Thank you. The changes were applied, so I'm closing it.
