### ISSUE TITLE
OpenTracing / Jaeger / Zipkin support?

### ISSUE THREAD

**Issue by lathspell** [louketo/louketo-proxy#635]
## Summary 

Are there any plans to support OpenTracing or Zipkin's X-B3-Header?

## Why?

Would benefit debugging as Gatekeeper ist usually just one of many proxies and apps a request goes through.

## How

Maybe using https://github.com/opentracing/opentracing-go

## Acceptance criteria

OpenTracing or B3-HTTP-Header are injected if not presend.

**Comment by abstractj** [comment]
@lathspell there's nothing planned at the moment, but I'd be more than happy to review a design proposal. @stianst what do you think?

**Comment by lathspell** [comment]
Have a look at this fork which already implements it. The pull request sadly includes unrelated stuff as well but the tracing.go file looks pretty easy: https://github.com/oneconcern/keycloak-gatekeeper/pull/27

**Comment by abstractj** [comment]
@lathspell if this is something that you would like to propose or implement, please start a design proposal. So we can discuss the motivation and the use case scenarios for this.

For now I'm closing this issue, as your question was already answered. But please reopen, if that's not the case.
