### ISSUE TITLE
What happened to the *Keycloak* Gatekeeper project?

### ISSUE THREAD

**Issue by lathspell** [louketo/louketo-proxy#636]
I was looking for the Keycloak Gatekeeper project but redirected here. Maybe you could add a note why Gatekeeper has a new name and who "louketo" is?

**Comment by abstractj** [comment]
@lathspell Gatekeeper was renamed to Louketo and moved to this organization. All the details are here:
- https://groups.google.com/d/msg/keycloak-dev/oDyw94BWxM0/zc0J9R10BwAJ
- https://groups.google.com/d/msg/keycloak-dev/vj4OtXPyMRo/bRg-vm1bEAAJ

If you have any other questions, please let us know. For now, I'm closing this issue.

**Comment by lathspell** [comment]
Why not write a little note at the front page and the Keycloak page as well. Just to reassure people that their favourite OAuth proxy hasn't been hijacked. Also this would give it some credability as nobody has yet heard of Lou Keto...
