### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by shaunc** [louketo/louketo-proxy#648]
# Title

## Summary 

I would like to install via a helm chart. I see there is an old keycloak-proxy chart. Is there any plan to upgrade/replace this?

## Why?

Helm is a standard way to deploy to kubernetes.

## How

 I see you recently added a Dockerfile, and some manifests. Are these going to be packaged into a chart? Any visibility as to when?

**Comment by abstractj** [comment]
@shaunc this is out of the scope for the Louketo project. If this is something that you would like to see included, I'd suggest to create an issue at https://github.com/helm/charts or submit a PR.
