### ISSUE TITLE
Where can we find release notes for old versions of Gatekeeper?

### ISSUE THREAD

**Issue by Nuru** [louketo/louketo-proxy#680]
# Where can we find release notes for old versions of Gatekeeper?

## Summary 

Most people are upgrading to louketo-proxy from old versions of Gatekeeper. They would benefit from seeing the old release notes. 

## Why?

When upgrading and something fails, it would be helpful to see if it is because of a known breaking change in the evolution of Gatekeeper.

**Comment by abstractj** [comment]
All the release notes are available here https://github.com/louketo/louketo-proxy/releases. Please check each tag and you can see the notes there.
